weather_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: weather_user
      password: weather_pass
      port: 55432
      dbname: weather_db
      schema: public
      threads: 4